export const data = [
    {
        _id: "65a7991572cf2c17cd7d9402",
        name: "Blankets",
        category: "Clothing",
        image: "/public/Authenticity50_Cotton_Blankets.webp",
        location: "New York, NY",
        publisherId: "7",
        phone: "123-456-7890",
        details: "Gently used blankets in good condition",
        flexible: true,
    },
    {
        _id: "65a7991572cf2c17cd7d9403",
        name: "Canned Food",
        category: "Food",
        image: "/public/canned_food.jpg",
        location: "Chicago, IL",
        publisherId: "9",
        phone: "098-765-4321",
        details: "Unopened canned vegetables and fruits",
        flexible: false,
    },
    {
        _id: "65a7991572cf2c17cd7d9404",
        name: "Winter Coats",
        category: "Clothing",
        image: "/public/winter_coats.jpg",
        location: "Seattle, WA",
        publisherId: "11",
        phone: "555-1234",
        details: "Lightly used winter coats in various sizes",
        flexible: true,
    },
    {
        _id: "65a7991572cf2c17cd7d9405",
        name: "Utensils",
        category: "Household",
        image: "/public/Utensils.jpg",
        location: "Portland, OR",
        publisherId: "13",
        phone: "555-5678",
        details: "Used forks, spoons, knives",
        flexible: false,
    },
    {
        _id: "65a7991572cf2c17cd7d9406",
        name: "Shoes",
        category: "Clothing",
        image: "/public/Shoes.jpg",
        location: "Austin, TX",
        publisherId: "15",
        phone: "555-9101",
        details: "Gently used shoes for men, women, children",
        flexible: true,
    },
    {
        _id: "65a7991572cf2c17cd7d9407",
        name: "Towels",
        category: "Household",
        image: "/public/Towels.jpg",
        location: "Miami, FL",
        publisherId: "7",
        phone: "222-3333",
        details: "Used bath and hand towels",
        flexible: true,
    },
    {
        _id: "65a7991572cf2c17cd7d9408",
        name: "Pillows",
        category: "Household",
        image: "/public/Pillows.jpg",
        location: "Dallas, TX",
        publisherId: "9",
        phone: "333-4444",
        details: "Gently used pillows",
        flexible: false,
    },
    {
        _id: "65a7991572cf2c17cd7d9409",
        name: "Backpacks",
        category: "Accessories",
        image: "/public/Backpacks.jpg",
        location: "San Francisco, CA",
        publisherId: "11",
        phone: "444-5555",
        details: "Used adult and kids backpacks",
        flexible: true,
    },
    {
        _id: "65a7991572cf2c17cd7d940a",
        name: "Dishes",
        category: "Household",
        image: "/public/Dishes.jpg",
        location: "Columbus, OH",
        publisherId: "13",
        phone: "555-6666",
        details: "Assorted used plates, bowls, cups",
        flexible: false,
    },
];
